# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1eabf34bb3e3799be0c946ddc34af7884f527acd1a644b7173f687311c2c8c30ede09ded6884a421486105a696e8865ff33e0f449ddd4ce4bd22e43db608f999

test:
  secret_key_base: fa1d2fa5a88d146a00f5769382d706406cadd19a309fac96f3e3a04e468b7e83e4a2547c31cf2b7b1fc0fda0ebbb0a0714214d9cdaa01f68bc94f0944efd51f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
